# Generated by Django 3.2.9 on 2021-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likecount',
            field=models.ImageField(blank=True, default=0, upload_to='', verbose_name='like_count'),
        ),
    ]
